### ISSUE TITLE
Avatar out of bounds of circle

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [zamplyy/react-native-nice-avatar#11]
A avatar is outside the circle

Example:
<img width="160" alt="Bildschirmfoto 2022-06-09 um 11 57 35" src="https://user-images.githubusercontent.com/33295329/172820700-a22237f3-1048-47ae-bbae-92935800c460.png">

Original from react-nice-avatar:
<img width="161" alt="Bildschirmfoto 2022-06-09 um 11 58 12" src="https://user-images.githubusercontent.com/33295329/172820824-28e237e6-cfb6-46b7-b118-0aa2fca29da1.png">

**Comment by zamplyy** [comment]
I'll have a look and fix probably this afternoon. Thanks for noticing

**Comment by zamplyy** [comment]
Should be fixed in 1.1.1

**Comment by NilsBaumgartner1994** [comment]
Works like a charm now

<img width="527" alt="Bildschirmfoto 2022-06-10 um 11 37 51" src="https://user-images.githubusercontent.com/33295329/173037512-2e093428-df42-4070-80f9-6a1157d57b04.png">
